### ISSUE TITLE
Failed to register a custom SMS provider

### ISSUE THREAD

**Issue by brieucthomas** [K-Phoen/KPhoenSmsSenderBundle#4]
Hello,

I try to register a custom SMS provider and I get this error:

``` sh
  [LogicException]
  No factory found for the provider "acme"
```

This is the KPhoenSmsSenderBundle bundle configuration:

``` yaml
# config.yml
k_phoen_sms_sender:
    pool:         ~
    http_adapter: curl
    providers:    [acme]

    acme:    ~ 
```

This is my bundle services:

``` xml
<!-- services.xml -->
<service id="sms.provider.factory.acme"
         class="AcmeBundle\DependencyInjection\SMS\Factory\AcmeProviderFactory">
    <tag name="sms.provider.factory" />
</service>
<service id="sms.provider.acme" class="AcmeBundle\SMS\Provider\AcmeProvider">
    <argument type="service" id="sms.http_adapter" />
</service>
```

My service tagged with  `sms.provider.factory` is not loaded by the KPhoenSmsSenderBundle.
